### ISSUE TITLE
Can this be hosted on Heroku?

### ISSUE THREAD

**Issue by juliustip** [phazyy/statuspage#1]
Just wanted to know if this can be hosted on Heroku.

**Comment by ahstn** [comment]
I haven't got much experience with Heroku, but if it can run Docker containers, which I'm assuming it can, then yeah.

They seem to have some documentation here on deploying Docker-based apps on their platform: https://devcenter.heroku.com/articles/container-registry-and-runtime

**Comment by juliustip** [comment]
Thanks, will check it out.
BTW, i kept getting this error when trying to install local:
`ERROR: repository cachet not found: does not exist or no pull access`

If i may ask, are you looking at pushing the docker version or the normal version in your docker-compose.yml? `image: cachet:2.3` needs to be changed to `image: cachethq/docker` if targeting the docker version.

**Comment by ahstn** [comment]
Yeah it's a leftover from me testing out a personal build of the Cachet docker image. I've updated the docker-compose.yml to use the official image now.
