### ISSUE TITLE
Change component status if metric is down

### ISSUE THREAD

**Issue by juliustip** [phazyy/statuspage#3]
Anyway to make this happen?
E.G if 205ms for 15mins, it should change status to partial outage. At 30 mins, it should change to Major.

**Comment by ahstn** [comment]
I believe this feature already exists in Cachet-Monitor (https://github.com/CastawayLabs/cachet-monitor#features).

I haven't tested it but if you lower the timeout in the monitor.yml to 205ms (0.205) it should work.
