### ISSUE TITLE
SQL data sample

### ISSUE THREAD

**Issue by juliustip** [phazyy/statuspage#4]
Would like to know if you could come up with a sample SQL Data for normal Cachet.
I want to host this using Cpanel instead.

**Comment by ahstn** [comment]
Firstly, apologies for the late, late reply. I've been busy with uni work as the project [readme] now reflects, but I'll answer this for anyone else who comes across the project.

Sample SQL data lives under the [sql folder] in the repo with the SQL required to setup the Cachet instance. The customising section in the [sql readme] explains how to alter the queries to insert your own pre-defined data.

[readme]: https://github.com/ahstn/statuspage/blob/master/README.md
[sql folder]: https://github.com/ahstn/statuspage/tree/master/sql
[sql readme]: https://github.com/ahstn/statuspage/blob/master/sql/README.md#customising
